version: '3.7'

services:
  web:
    build: 
      context: .
      args:
       - ENV=${ENV}
    image: cicd_test
    command: >
      bash -c "sleep 20 
      && python manage.py runserver 0.0.0.0:8000 --insecure"
    environment:
      - ENVIRONMENT=development
        # Double dollar $$ used to represent $ if present 
      - SECRET_KEY=/run/secrets/django_secret_key
        # Set to debugging for local testing unless environment variable states otherwise
      - DEBUG=${DEBUG:-1}
      - POSTGRES_PASSWORD=/run/secrets/postgres_password
    secrets:
      - django_secret_key
      - postgres_password
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      testing_net:
        ipv4_address: 172.25.0.3

  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password
    ports:
      - 5432:5432
    volumes:
      - ./example_data
        #    Add volume for local dev/testing
#    volumes:
#      - ~/docker_volumes/postgres_bookstore:/var/lib/postgresql/data/
    networks:
      testing_net:
        ipv4_address: 172.25.0.2

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16

secrets:
  postgres_password:
    file:
      ./secrets/postgres_password
  django_secret_key:
    file:
      ./secrets/djangobooks_key
